### PR TITLE
mediatek: filogic: Add support ASUS RT-AX57M

### LINKED ISSUE #17119: "Segmentation fault" error when flashing openWRT factory image to RT-AX54 (ASUS RTAX-1800S)
### Describe the bug

Hello,
I attempted to flash the openWRT factory firmware via mtd-write, but I get a "Segmentation fault" message in the terminal. This is on a brand new ASUS RT-AX1800S unit.

Some details:
Model: ASUS RT-AX1800S V2
PN: 901G08X0-MA1C0V
openWRT Factory code: openwrt-23.05.4-ramips-mt7621-asus_rt-ax54-squashfs-factory.bin

### OpenWrt version

Unable to run

### OpenWrt release

Unable to run

### OpenWrt target/subtarget

Unable to run

### Device

Unable to run

### Image kind

Official downloaded image

### Steps to reproduce

copy the firmware file from computer to router
`cat openwrt-23.05.4-ramips-mt7621-asus_rt-ax54-squashfs-factory | ssh admin@device "cat > /root/openwrt-23.05.4-ramips-mt7621-asus_rt-ax54-squashfs-factory"`

ssh in to router
`shh admin@192.168.50.1`

Flash the firmware
`mtd-write -i openwrt-23.05.4-ramips-mt7621-asus_rt-ax54-squashfs-factory -d Kernel`

### Actual behaviour

Message "Segmentation fault" is displayed on the terminal a few seconds after executing `mtd-write` command

### Expected behaviour

First time doing this (flashing firmware), so expect some message indicating success, and also openWRT firmware to load next time router is power cycled.

### Additional info

My understanding is that the RT-AX1800S is supported by openWRT AX54 firmware. This is a brand new router, not sure if it comes with a different memory chip which may not be compatible with the released of openWRT mentioned

### Diffconfig

_No response_

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

### LINKED ISSUE #17198: mtd-write "Segmentation fault" error when flashing openWRT factory image to ASUS RT-AX1800S (RT-AX54)
### Describe the bug

I attempted to flash the openWRT factory firmware via mtd-write, but I get a "Segmentation fault" message in the terminal. This is on a brand new ASUS RT-AX1800S unit.

### OpenWrt version

r24012-d8dd03c46f

### OpenWrt release

23.05.4

### OpenWrt target/subtarget

ramips/mt7621

### Device

asus rt-ax54

### Image kind

Official downloaded image

### Steps to reproduce

- following directions from device page https://openwrt.org/toh/asus/rt-ax54
- ssh into device as delivered (is running Asus firmware 3.0.0.4_388_33381-g0cf44bd)
- download firmware https://downloads.openwrt.org/releases/23.05.4/targets/ramips/mt7621/openwrt-23.05.4-ramips-mt7621-asus_rt-ax54-squashfs-factory.bin with wget
- verify sha256sum
- mtd-write segfaults , both from root's dir in `/tmp` and from `/jffs`

### Actual behaviour

- mtd-write segfaults , both from root's dir in `/tmp` and from `/jffs`

```
linksys@RT-AX1800S-BC38:/tmp/home/root# uname -a
Linux RT-AX1800S-BC38 5.4.225 #1 SMP Thu Mar 28 14:46:29 CST 2024 aarch64 ASUSWRT

linksys@RT-AX1800S-BC38:/tmp/home/root# wget https://downloads.openwrt.org/releases/23.05.4/targets/ramips/mt7621/openwrt-23.05.4-ramips-mt7621-asus_rt-ax54-squashfs-factory.bin
[...]
openwrt-23.05.4-ramips-mt7621- 100%[====================================================>]   9.00M  8.41MB/s    in 1.1s    
2024-12-07 09:41:29 (8.41 MB/s) - 'openwrt-23.05.4-ramips-mt7621-asus_rt-ax54-squashfs-factory.bin' saved [9437184/9437184]

linksys@RT-AX1800S-BC38:/tmp/home/root# openssl sha256 < openwrt-23.05.4-ramips-mt7621-asus_rt-ax54-squashfs-factory.bin
(stdin)= b96143923e5707fa0bc75308cd5c3b77718dc2316230596273404f14cbb9e036

linksys@RT-AX1800S-BC38:/tmp/home/root# mtd-write -i openwrt-23.05.4-ramips-mt7621-asus_rt-ax54-squashfs-factory.bin -d Kernel ; date
Segmentation fault

# also fails from /jffs

/jffs/tmp# mtd-write -i openwrt-23.05.4-ramips-mt7621-asus_rt-ax54-squashfs-factory.bin -d Kernel
Segmentation fault

# dmesg

nvram_commit(): pid 1 comm [init]
_nvram_free: 1(init) nvram_idx(1 / 2)
found private data block and skip it
nvram_commit(): pid 2048 comm [aaews]
_nvram_free: 2048(aaews) nvram_idx(0 / 2)
found private data block and skip it
value=1, hook is enabled now!
7981@C23L3rax0,DfsCacEndUpdate() 3310: [RDM] CAC end. Enable MAC TX.
nvram_commit(): pid 2723 comm [firmware_check_]
_nvram_free: 2723(firmware_check_) nvram_idx(1 / 2)
found private data block and skip it
potentially unexpected fatal signal 11.
===DDD===
7f8e5b0000 - 7f8e5d1000, [libgcc_s.so.1]
7f8e5d3000 - 7f8e5f0000, [libcodb.so]
7f8e5f2000 - 7f8e6ea000, [libsqlite3.so.0.8.6]
7f8e6f1000 - 7f8e712000, [libev.so.4.0.0]
7f8e714000 - 7f8e726000, [libasuslog.so]
7f8e728000 - 7f8e747000, [libjansson.so]
7f8e749000 - 7f8e76c000, [liblldpctl.so.4.8.0]
7f8e770000 - 7f8e7b4000, [libamas-utils.so]
7f8e7b6000 - 7f8e7ce000, [libjson-c.so.2.0.2]
7f8e7d0000 - 7f8e831000, [libcurl.so.4.8.0]
7f8e835000 - 7f8e84b000, [libletsencrypt.so]
7f8e84d000 - 7f8e86e000, [libvpn.so]
7f8e871000 - 7f8e882000, [libcfgmnt.so]
7f8e884000 - 7f8e8b3000, [libbwdpi.so]
7f8e8b8000 - 7f8e936000, [libssl.so.1.1]
7f8e93f000 - 7f8eb76000, [libcrypto.so.1.1]
7f8eb99000 - 7f8ec18000, [libshared.so]
7f8ec29000 - 7f8ec3b000, [libnvram.so]
7f8ec3d000 - 7f8ec5e000, [libconn_diag.so]
7f8ec62000 - 7f8ece2000, [libc.so]
CPU: 1 PID: 3147 Comm: mtd-write Tainted: P                  5.4.225 #1
Hardware name: RT-AX57M (DT)
pstate: 00000000 (nzcv daif -PAN -UAO)
pc : 000000000045ef90
lr : 000000000045ef90
sp : 0000007fef027d50
x29: 0000007fef027d50 x28: 0000007f8ecf5000
x27: 0000000000000005 x26: 0000000000000000
x25: 0000007f8e76f440 x24: 000000000050fdf4
x23: 0000000000000000 x22: 0000000000000000
x21: 00000000ffffffff x20: 0000000000900000
x19: 0000007fef027f80 x18: 0000000000000000
x17: 0000007f8eca0f7c x16: 0000000000560090
x15: 0000000000800000 x14: 0000000000800000
x13: 000000000050fe2f x12: 0000007fef027a8c
x11: 00000000ffffffff x10: 0000007fef027fba
x9 : 000000000000000a x8 : 00000000000000d7
x7 : fefefefefefefeff x6 : 0000000000000000
x5 : 0000000000000000 x4 : 0000000000000002
x3 : 0000000000000000 x2 : 0000000000000000
x1 : 0000000000900000 x0 : 0000000000000000



### Expected behaviour

- mtd-write succeeds, allowing me to boot into openwrt

### Additional info

Because I'm not yet running openwrt, guessed required field "OpenWrt version" from https://downloads.openwrt.org/releases/23.05.4/targets/ramips/mt7621/version.buildinfo

I saw a recent very similar issue (but with less info provided, so it's tagged invalid): #17119

### Diffconfig

_No response_

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

### PR DESCRIPTION
**Pull request by theofficialgman**
patches to add new devices should not stay in forks of the repo for over a year @remittor https://github.com/openwrt/openwrt/issues/17198#issuecomment-2525496674 https://github.com/openwrt-xiaomi/openwrt/commit/81bfbed6eefb29ba35499ae09bf80d13ae2496b1

I am new to openwrt (though not embedded system development) and am willing to help push these changes upstream and help where able debug any issues with the current patchset.

see https://github.com/openwrt/openwrt/commit/50d9ca6e5a04724e4263a348bdbe5ff4b1c43998 for details on installing trx

closes https://github.com/openwrt/openwrt/issues/17198
closes https://github.com/openwrt/openwrt/issues/17119

### CODE REVIEW

**Comment by theofficialgman** [comment]
Just for confirmation, I have built and run this
image

Also would like to backport this to the stable branch once this is accepted.

**Comment by theofficialgman** [comment]
@blocktrron @achterin Any feedback on this? I would appreciate anything you have to share on the process for getting this router model merged. I'd like to add it to the wiki as well so if either of you are familiar with that process please let me know the details or point me to the resources for that.

File: target/linux/mediatek/filogic/base-files/etc/board.d/01_leds [hunk 1]
```diff
@@ -20,7 +20,8 @@ acer,predator-w6x)
 	ucidef_set_led_netdev "wan" "wan" "rgb:status" "eth1"
 	;;
 asus,rt-ax52|\
-snr,snr-cpe-ax2)
+snr,snr-cpe-ax2|\
+asus,rt-ax57m)
```
Comment (achterin) [inline target/linux/mediatek/filogic/base-files/etc/board.d/01_leds]: sort alphabetically

File: target/linux/mediatek/filogic/base-files/etc/board.d/02_network [hunk 2]
```diff
@@ -35,6 +35,9 @@ mediatek_setup_interfaces()
 	arcadyan,mozart)
 		ucidef_set_interfaces_lan_wan "lan0 eth1" eth2
 		;;
+	asus,rt-ax57m)
```
Comment (achterin) [inline target/linux/mediatek/filogic/base-files/etc/board.d/02_network]: there should be no need to add this, as this is the default case. see line 172

File: target/linux/mediatek/filogic/base-files/lib/upgrade/platform.sh [hunk 3]
```diff
@@ -134,6 +134,7 @@ platform_do_upgrade() {
 		CI_ROOTPART="rootfs"
 		emmc_do_upgrade "$1"
 		;;
+	asus,rt-ax57m|\
```
Comment (achterin) [inline target/linux/mediatek/filogic/base-files/lib/upgrade/platform.sh]: sort alphabetically

File: target/linux/mediatek/filogic/base-files/lib/upgrade/platform.sh [hunk 4]
```diff
@@ -339,6 +340,7 @@ platform_pre_upgrade() {
 	local board=$(board_name)
 
 	case "$board" in
+	asus,rt-ax57m|\
```
Comment (achterin) [inline target/linux/mediatek/filogic/base-files/lib/upgrade/platform.sh]: sort alphabetically

File: target/linux/mediatek/dts/mt7981b-asus-rt-ax57m.dts [hunk 5]
```diff
@@ -0,0 +1,343 @@
...
+		};
+
+		wan {
+			function = LED_FUNCTION_WAN;
+			color = <LED_COLOR_ID_BLUE>;
+			gpios = <&pio 8 GPIO_ACTIVE_LOW>;
+		};
+
+		led_system: system {
+			label = "blue:system";
```
Comment (achterin) [inline target/linux/mediatek/dts/mt7981b-asus-rt-ax57m.dts]: maybe replace label with function and color attributes as well. LED_FUNCTION_STATUS as function should be fitting

**Comment by achterin** [comment]
Your commit lacks information about the device hardware, flash instructions and the mac assignment.

File: target/linux/mediatek/dts/mt7981b-asus-rt-ax57m.dts (hunk 5 above)
Comment (theofficialgman) [reply target/linux/mediatek/dts/mt7981b-asus-rt-ax57m.dts]: I'll refer back to https://github.com/openwrt/openwrt/commit/50d9ca6e5a04724e4263a348bdbe5ff4b1c43998 which it seems you co-authored with @liudongdongdong7397 for the label on that router.

**Comment by theofficialgman** [comment]
> Your commit lacks information about the device hardware, flash instructions and the mac assignment.

added hardware and flash instructions. not sure about the mac assignment details other than what is done in `11_fix_wifi_mac`. none of the other routers that use the same codepath provided any mac details for them.

**Comment by theofficialgman** [comment]
there is only one MAC on the box for my router and it matches the one that the script pulls from the mtd ubi Factory partition at offset `0x4`. All the interfaces use it except phy0 (2.4Ghz) which tracks with what the script does.

I don't know what MAC ranges asus assigns to these routers so can't say what the possible values could be.

File: target/linux/mediatek/dts/mt7981b-asus-rt-ax57m.dts (hunk 5 above)
Comment (achterin) [reply target/linux/mediatek/dts/mt7981b-asus-rt-ax57m.dts]: seems like i've missed that in my own commit as well then - no need to keep doing it this way, if there is a "better approach" - but maybe @blocktrron has an opinion on this.

**Comment by achterin** [comment]
> there is only one MAC on the box for my router and it matches the one that the script pulls from the mtd ubi Factory partition at offset `0x4`. All the interfaces use it except phy0 (2.4Ghz) which tracks with what the script does.
> 
> I don't know what MAC ranges asus assigns to these routers so can't say what the possible values could be.

we dont need the mac-ranges of asus, just the assignments on each network adapter of this device - see https://github.com/openwrt/openwrt/commit/13dc286814c646a2f03dc27e5bf2a34206e0242d as an example.

just a small question about the alt models: have you tried them all or how did you verify that they are indeed identical?

other than these two points, the pr looks in good shape to me. now its time to wait for someone with commit access :)

**Comment by theofficialgman** [comment]
> we dont need the mac-ranges of asus, just the assignments on each network adapter of this device - see [13dc286](https://github.com/openwrt/openwrt/commit/13dc286814c646a2f03dc27e5bf2a34206e0242d) as an example.

gotcha, will do

> just a small question about the alt models: have you tried them all or how did you verify that they are indeed identical?

The models come from https://www.snbforums.com/threads/asus-rt-ax1800s-v2-firmware-version-3-0-0-4-388_33965-2025-10-22.95966/ who validated that all the official firmware have the same firmware hash and same hardware. I personally have the ASUS RT-AX1800S V2 (no other model).

**Comment by achterin** [comment]
looks good to me now. maybe some openwrt core-dev can give his opinion about the system-led, but other than that i this this pr is good to go

**Review by achterin — APPROVED** [review]

File: target/linux/mediatek/dts/mt7981b-asus-rt-ax57m.dts (hunk 5 above)
Comment (theofficialgman) [reply target/linux/mediatek/dts/mt7981b-asus-rt-ax57m.dts]: Just for reference, this is what the default LED configuration is as is.

image

I am not sure what OpenWRT's preference is with LED configuration but I would think it would be best if all the LEDs were configured like "stock" (ie: activity lights work out of the box).

It seems like to me the `linux,default-trigger` is ignored since those LEDs don't show in the default configuration (screenshot above).

Looking at another OpenWRT device (the only other one I have), a TP-Link Archer A7 v5 on 24.10, it has the following default config

image

and again its default triggers seem to be ignored?

https://github.com/openwrt/openwrt/blob/984a2197817e7c6e7266ebfa5cde305029d18b1b/target/linux/ath79/dts/qca9563_tplink_archer-x7-v5.dtsi#L17-L83

Comment (achterin) [reply target/linux/mediatek/dts/mt7981b-asus-rt-ax57m.dts]: > It seems like to me the `linux,default-trigger` is ignored since those LEDs don't show in the default configuration (screenshot above).

i would say its more like the other way around - luci does not display linux,default-trigger correctly. if the default-trigger was not working, your wifi leds would not blink on throughput activity. as far as i understand it, it just sets the trigger for that led in sysfs. you can check this by cating `/sys/class/leds/led-name/trigger`.

Comment (theofficialgman) [reply target/linux/mediatek/dts/mt7981b-asus-rt-ax57m.dts]: gotcha, yeah my wifi leds don't work but it seems like thats because gpios from @remittor are wrong (at least for my RT-AX1800S V2). @remittor can you confirm that your LED config works for you or did you just copy it from somewhere else and not actually correct it?

here is what I determined them to be based on https://openwrt.org/docs/techref/hardware/port.gpio

power (blue): 4 Active High
internet (blue): 5 Active Low
internet (red): 6 Active Low
lan (blue): 7 Active Low
2.4g (blue): 8 Active Low (assigned in current dts to wan.... @remittor)
5g (blue): 9 Active Low

Comment (achterin) [reply target/linux/mediatek/dts/mt7981b-asus-rt-ax57m.dts]: there is also a script somewhere in the wiki that helps with finding the correct gpios by triggering them one by one. you just need to set the correct gpiobase in that one, which you can find by just looking at the sysfs path it wants to query.
sorry, but leds assignment should work before this gets merged.

**Review by achterin — CHANGES_REQUESTED** [review]
LED assignment needs to work before this can get merged.

**Comment by gmesm** [comment]
WAN doesn't work (previously reported in forum thread and I have now confirmed). I've been trying to get the GPL sources from Asus but support is taking it's time.

**Comment by theofficialgman** [comment]
Even with the above fix to the device tree it seems like WAN still doesn't work. I don't see any other OpenWRT devices that uses this format for the wan ethernet but that is what the official device tree does.

[dts.txt](https://github.com/user-attachments/files/23224252/dts.txt)

**Comment by achterin** [comment]
Sometimes vendors dont know how to properly configure everything in the device tree and use the programmatic approach instead. netgear for example used a mixture of dts and c code in their gpl source for the Orbi devices to define the hardware. Look for GPIO_ in the sources, maybe they are defined that way.

**Comment by theofficialgman** [comment]
> Look for GPIO_ in the sources, maybe they are defined that way.

yes will do once Asus complies with the GPL and sends the sources to me, although the led gpio are fine now that I fixed them, just WAN is problematic (they must have done something in the kernel driver to get it to work).

**Comment by theofficialgman** [comment]
Tagging @dangowrt as well since they did all the MT7981B (back)porting as well. As soon as I get the GPL sources from ASUS I'll upload them somewhere for everyone to view and see if I can spot anything in them myself.

**Review by dangowrt — APPROVED** [review]

**Comment by theofficialgman** [comment]
I did a teardown of my unit to make sure there wasn't an unexpected additional ethernet transceiver and there was not.

PXL_20251101_191546940
PXL_20251101_191615255
PXL_20251101_191643096
PXL_20251101_191734122
PXL_20251101_191554658

File: target/linux/mediatek/dts/mt7981b-asus-rt-ax57m.dts [hunk 6]
```diff
@@ -0,0 +1,360 @@
...
+	gmac1: mac@1 {
+		/* WAN */
+		compatible = "mediatek,eth-mac";
+		reg = <1>;
+		nvmem-cells = <&macaddr_factory_4>;
+		nvmem-cell-names = "mac-address";
+		label = "wan";
+		phy-mode = "2500base-x";
+
+		fixed-link {
```
Comment (dangowrt) [inline target/linux/mediatek/dts/mt7981b-asus-rt-ax57m.dts]: This is wrong. The device is using the internal built-in 1GE PHY of the MT7981 SoC as WAN port. You should reference the internal PHY and also assign the correct MAC address.

**Review by dangowrt — CHANGES_REQUESTED** [review]
Taking a closer look it is quite obvious why the WAN port won't work.

File: target/linux/mediatek/dts/mt7981b-asus-rt-ax57m.dts (hunk 6 above)
Comment (theofficialgman) [reply target/linux/mediatek/dts/mt7981b-asus-rt-ax57m.dts]: This is how it's defined in the official device tree (https://github.com/openwrt/openwrt/pull/20491#issuecomment-3465904148) and the Mac of the WAN is the same as LAN in stock firmware as well.

Regardless though, this was originally set as gigabit and that also doesn't work. See the change here for how it was originally https://github.com/openwrt/openwrt/pull/20491/commits/cc82826aa80d228478c2828a0e9219aa6089320f

Comment (theofficialgman) [reply target/linux/mediatek/dts/mt7981b-asus-rt-ax57m.dts]: My best guess is on stock firmware they use phy-mode 2500base-x (like I know from my stock devicetree dump https://github.com/openwrt/openwrt/pull/20491#issuecomment-3465904148 , MACs redacted but they are the same) and use rate matching to support the lower link speeds. Without the firmware source yet I can't really say though.

Comment (dangowrt) [reply target/linux/mediatek/dts/mt7981b-asus-rt-ax57m.dts]: Well, you posted pictures of the board and there isn't any additional PHY chip apart from the MT7531 switch IC connected to GMAC0. So GMAC1 must be the internal PHY of the MT7981, so please try
```
	gmac1: mac@1 {
		compatible = "mediatek,eth-mac";
		reg = <1>;
		phy-mode = "gmii";
		phy-handle = <&int_gbe_phy>;
		nvmem-cells = <&macaddr_factory_4>;
		nvmem-cell-names = "mac-address";
		openwrt,netdev-name = "wan";
	};
```

Comment (theofficialgman) [reply target/linux/mediatek/dts/mt7981b-asus-rt-ax57m.dts]: Already tried all of the below with failed results:

(what you asked for)
```
	gmac1: mac@1 {
		compatible = "mediatek,eth-mac";
		reg = <1>;
		phy-mode = "gmii";
		phy-handle = <&int_gbe_phy>;
		nvmem-cells = <&macaddr_factory_4>;
		nvmem-cell-names = "mac-address";
		openwrt,netdev-name = "wan";
	};
```

what I've seen in the ax52 target
```
	gmac1: mac@1 {
		/* WAN */
		compatible = "mediatek,eth-mac";
		reg = <1>;
		nvmem-cells = <&macaddr_factory_4>;
		nvmem-cell-names = "mac-address";
		phy-mode = "gmii";
		phy-handle = <&phy0>;
		label = "wan";
	};

	mdio: mdio-bus {
		#address-cells = <1>;
		#size-cells = <0>;

		phy0: ethernet-phy@0 {
			compatible = "ethernet-phy-id03a2.9461";
			reg = <0>;
			phy-mode = "gmii";
			#nvmem-cells = <&phy_calibration>;
			#nvmem-cell-names = "phy-cal-data";
		};
```

and what is currently in the tree (note I also delete the ethernet-phy0 node in this below test since its not needed or present in stock device tree)

```
	gmac1: mac@1 {
		/* WAN */
		compatible = "mediatek,eth-mac";
		reg = <1>;
		nvmem-cells = <&macaddr_factory_4>;
		nvmem-cell-names = "mac-address";
		label = "wan";
		phy-mode = "2500base-x";

		fixed-link {
			speed = <2500>;
			full-duplex;
			pause;
		};
	};
```

As I mentioned before, what is in this PR now matches the stock device tree and the kernel output in OpenWRT matches the stock firmware kernel output (ie: I see both the WAN and LAN ports initialize as 2500base-x in the stock firmware dmesg logs).

Comment (theofficialgman) [reply target/linux/mediatek/dts/mt7981b-asus-rt-ax57m.dts]: @dangowrt any thoughts on that ^ ? Let me know if I can help with anything while we are still waiting for stock source code (the Asus engineers are being slow to prepare it for customer support).

Comment (dangowrt) [reply target/linux/mediatek/dts/mt7981b-asus-rt-ax57m.dts]: I'm convinced that it must be the internal PHY, simply because there isn't any other PHY chip on that board. Try with my suggestion, but use `phy-mode = "internal";` and show me the complete bootlog with that.

Comment (theofficialgman) [reply target/linux/mediatek/dts/mt7981b-asus-rt-ax57m.dts]: not sure if you wanted the full logread or just dmesg so I attached both. only thing I redacted was the MAC (not that you could reasonably do anything with it anyway).

[logread.txt](https://github.com/user-attachments/files/23433260/logread.txt)

[dmesg.txt](https://github.com/user-attachments/files/23433261/dmesg.txt)

and the current dts in my tree (just renamed as txt for github)
[mt7981b-asus-rt-ax57m.dts.txt](https://github.com/user-attachments/files/23433310/mt7981b-asus-rt-ax57m.dts.txt)

**Comment by XKangs** [comment]
I find a file on https://github.com/openwrt-xiaomi/openwrt/blob/xq-24.10/target/linux/mediatek/dts/mt7981b-asus-rt-ax57m.dts
```
	gmac1: mac@1 {
		/* WAN */
		compatible = "mediatek,eth-mac";
		reg = <1>;
		nvmem-cells = <&macaddr_factory_4>;
		nvmem-cell-names = "mac-address";
		phy-mode = "gmii";
		phy-handle = <&phy0>;
		label = "wan";
	};
```
seems like his WAN port is working...but I have not yet flash it to my router.

**Comment by theofficialgman** [comment]
> seems like his WAN port is working...but I have not yet flash it to my router.

Sorry @XKangs, its not, please read all the comments above. What you linked is the original dts from @remittor that doesn't work and has been confirmed not to work by myself and other users on the forum in the first post and github issue in the first post.

**Comment by XKangs** [comment]
> > seems like his WAN port is working...but I have not yet flash it to my router.
> 
> Sorry @XKangs, its not, please read all the comments above. What you linked is the original dts from @remittor that doesn't work and has been confirmed not to work by myself and other users on the forum in the first post and github issue in the first post.

sorry about my misunderstanding. I notice on the post (https://github.com/openwrt/openwrt/issues/15348#issuecomment-2499740405) mentions that we can use ethtools to force the link speed/autoneg or disable the energy-efficient-ethernet (https://github.com/openwrt/openwrt/issues/15348#issuecomment-2638037706 ). I am not sure if it is helpful because on the other post (https://forum.openwrt.org/t/openwrt-support-for-asus-rt-ax57m-ax1800s-v2/208534/5) saying that this method is not work on AX57M

**Comment by theofficialgman** [comment]
ASUS technical product team still needs 1-2 weeks to prepare the GPL sources. I will post it once received.

**Comment by theofficialgman** [comment]
GPL sources are up now. See https://www.asus.com/networking-iot-servers/wifi-routers/asus-wifi-routers/rt-ax57m/helpdesk_download?model2Name=RT-AX57M for download (same SHA-256 on ASUS RT-1800S V2 as expected, didn't check the other models).

**Comment by theofficialgman** [comment]
I think this code in `init-ralink.c` along with the code in `wan.c` is interesting

```
#if defined(RTCONFIG_MT798X)
void wan_force_link_sp(int unit)
{
	int wan_force_link, value;
	int port;

	if (find_word(nvram_safe_get("rc_support"), "wan_sp") == NULL)
		return;

	if (unit != 0)
		return;

#if defined(TUFAX4200) || defined(TUFAX6000)
	port = 6;
#elif defined(RTAX59U) || defined(RTAX52)
	port = 1;
#elif defined(RTAX57M)
	port = 4;
#elif defined(PRTAX57_GO)
	port = 0;
#else
#error port need to be defined
#endif

	wan_force_link = nvram_get_int("wan0_force_link");
	switch (wan_force_link) {
		case 1:	//10Mbps
			value = 0;
			break;
		case 2:	//100Mbps
			value = 0x2000;
			break;
		case 3:	//1000Mbps
			value = 0x0040;
			break;
		case 4:	//2500Mbps
			value = 0x2040;
			break;
		case 0:	//auto
		default:
			value = 0x3040;
			break;
	}
	doSystem("mii_mgr -s -p %d -d 0 -r 0 -v 0x%x", port, value);
}
#endif	//RTCONFIG_MT798X
```

```
start_wan_if(int unit)
...
	update_wan_state(prefix, WAN_STATE_INITIALIZING, 0);
#if defined(RTCONFIG_MT798X)
	void wan_force_link_sp(int unit);
	wan_force_link_sp(unit);
#endif
```

**Comment by theofficialgman** [comment]
checking on stock `wan0_force_link` is `0` in nvram but port 4 is set to 0000 which is.... strange

```
admin@RT-AX1800S-A138:/tmp/home/root# nvram get wan0_force_link
0
```
```
admin@RT-AX1800S-A138:/tmp/home/root# mii_mgr -g -p 4 -r 0
Get: phy[4].reg[0] = 0000
admin@RT-AX1800S-A138:/tmp/home/root# mii_mgr -g -p 0 -r 0
Get: phy[0].reg[0] = 1040
admin@RT-AX1800S-A138:/tmp/home/root# mii_mgr -g -p 1 -r 0
Get: phy[1].reg[0] = 0000
admin@RT-AX1800S-A138:/tmp/home/root# mii_mgr -g -p 2 -r 0
Get: phy[2].reg[0] = 0000
admin@RT-AX1800S-A138:/tmp/home/root# mii_mgr -g -p 3 -r 0
Get: phy[3].reg[0] = 0000
admin@RT-AX1800S-A138:/tmp/home/root# mii_mgr -g -p 4 -r 0
Get: phy[4].reg[0] = 0000
admin@RT-AX1800S-A138:/tmp/home/root# mii_mgr -g -p 5 -r 0
Get: phy[5].reg[0] = 0000
```

**Comment by theofficialgman** [comment]
@dangowrt unless you are able to find the issue in the kernel drivers or userspace configuration (which it must be given that the same device tree works in the vendors image) I would like to merge this as is. Hopefully the vendor GPL sources that are now available that I linked above can help with root cause analysis but its beyond me at this point so maybe someone else can solve the WAN issue in the future.

File: target/linux/mediatek/dts/mt7981b-asus-rt-ax57m.dts (hunk 6 above)
Comment (theofficialgman) [reply target/linux/mediatek/dts/mt7981b-asus-rt-ax57m.dts]: FYI, with this https://github.com/openwrt/openwrt/pull/20491#discussion_r2484764039 I get no link when plugging in a cable at all (same as the other users reported).

```
root@Upstairs-OpenWrt:/sys/class/net/wan# cat carrier
0
root@Upstairs-OpenWrt:/sys/class/net/wan# cat operstate 
down
```

**Comment by theofficialgman** [comment]
@dangowrt Just bringing this up again since its been a few weeks ^.

**Comment by dangowrt** [comment]
Lets scan the MDIO bus using `mdio-tools`. Lets enable all 5 ports of the MT7531, I suspect the WAN port is basically just port 4 of the switch and port 0, 1, 2, 3 are the LAN ports. eth1 is probably not even used, why ever. Maybe they don't like the internal PHY of MT7981 and for some strange reason prefer the (slightly older but very similar) design of the MT7531 PHYs. Lets add that and see if it works.
```
			port@4 {
				reg = <4>;
				label = "wan";
			};
```
Or maybe ASUS made a bargain to buy MT7981B chips which got a broken 1GE PHY. Something like that...

**Comment by nam-van-nguyen** [comment]
According to a thread on OpenWrt support forum, the WAN issue may have something to do with 2.5G communication, and not due to "incorrect" port number designation.

 [flex](https://forum.openwrt.org/u/flex)

[theplagu3](https://forum.openwrt.org/t/openwrt-support-for-asus-rt-ax57m-ax1800s-v2/208534/3)
[Dec 2024](https://forum.openwrt.org/t/openwrt-support-for-asus-rt-ax57m-ax1800s-v2/208534/5?u=nng25)
Firmware flashed successfully for me as well, but no WAN connectivity over eth1. This is because auto negotiation is broken! 2.5G WAN port refuses to do 1G - TX packets seen but no RX packets. Using ethtool to force speed, duplex, or negotiation does not work.

**Comment by dangowrt** [comment]
If you think there is an actual 2.5G PHY maybe show the back side of the board (because on the front side I don't see any PHY) and scan the MDIO bus using `mdio-tools`.

**Comment by theofficialgman** [comment]
> If you think there is an actual 2.5G PHY maybe show the back side of the board (because on the front side I don't see any PHY) and scan the MDIO bus using `mdio-tools`.

back side is fully empty (save for some resistors/capacitors). sorry didn't take a picture because it was so empty when I tore it open. FCC images might be back up now since USA government is re-opened so you can check there if you don't believe me.

I'll comment on everything else later this week.

**Comment by theofficialgman** [comment]
> Lets scan the MDIO bus using `mdio-tools`.

Can't seem to install it on the self-build it seems

```
root@Upstairs-OpenWrt:~# apk add mdio-tools
ERROR: wget: exited with error 8
WARNING: updating and opening https://downloads.openwrt.org/snapshots/targets/mediatek/filogic/kmods/6.12.59-1-7b5da4fb9812629b9b908697bc150075/packages.adb: unexpected end of file
ERROR: unable to select packages:
  kmod-mdio-netlink (no such package):
    required by: mdio-tools-1.3.1-r3[kmod-mdio-netlink]
```

**Comment by theofficialgman** [comment]
> I suspect the WAN port is basically just port 4 of the switch and port 0, 1, 2, 3 are the LAN ports. eth1 is probably not even used, why ever.

Doubtful, have you even been reading my messages about the stock device tree, it does nothing with port 4 and it uses what is currently commited to this PR?
https://github.com/openwrt/openwrt/pull/20491#discussion_r2484158890
https://github.com/openwrt/openwrt/pull/20491#issuecomment-3589624905
But I will try and report back is a couple of hours.

**Comment by theofficialgman** [comment]
Ok the kernel recompiled very quickly (since my toolchain hasn't been updated since last time)..... @dangowrt port 4 is wan and works! I'll make the changes to this PR in a couple of hours (have to leave now).

**Comment by nam-van-nguyen** [comment]
This is very good news!  I don't know why, but I was able to upgrade the firmware to the initramfs.trx from OEM without any error message.  However, after that, I wasn't able to access the admin site nor able to get an IP address from it.  This is a local build based on the source, following the instruction (maybe I missed something).

Is there some specific configuration steps I need to follow?  I used this guide: https://openwrt.org/docs/guide-developer/toolchain/use-buildsystem

**Comment by theofficialgman** [comment]
> This is very good news! I don't know why, but I was able to upgrade the firmware to the initramfs.trx from OEM without any error message. However, after that, I wasn't able to access the admin site nor able to get an IP address from it. This is a local build based on the source, following the instruction (maybe I missed something).
> 
> Is there some specific configuration steps I need to follow? I used this guide: https://openwrt.org/docs/guide-developer/toolchain/use-buildsystem

@nam-van-nguyen nothing special. if this is your first time you are probably just using the wrong ip address (documentation should have it as well as the commit message for the commit in this PR)

its also very possible, if this is your first time, that you didn't actually enable the UI in make menuconfig. I know I didn't the first time 😆 (so had to ssh in or something and upload a new trx that way). I'll upload another image here soon.

**Comment by theofficialgman** [comment]
@hauke Is openwrt 25.12 due to release by the end of the year or early january? I'd love to get this device support into the next stable release, whatever that might be (24.10 series or 25.12 series), especially given that it fits the criteria for backporting where an existing device of the same name exists and results in user confusion where the other device of the same name's firmware does not work.

I have created PRs for this backport to the 24.10 and 25.12 branches below:

**Comment by warrenmr** [comment]
Amazing work, @theofficialgman!  I cannot find the sysupgrade file for this latest version that fixes the WAN port?

Looking forward to official support ...

**Comment by theofficialgman** [comment]
> Amazing work, @theofficialgman! I cannot find the sysupgrade file for this latest version that fixes the WAN port?

I've not uploaded it here yet. Currently building the 24.10 stable backport version and once I make sure that is all good I'll upload the 24.10 stable files here.

**Comment by theofficialgman** [comment]
@warrenmr @nam-van-nguyen see https://github.com/openwrt/openwrt/pull/21236#issuecomment-3678235358 for a build of the 24.10 stable version with functional WAN.

File: target/linux/mediatek/dts/mt7981b-asus-rt-ax57m.dts [hunk 7]
```diff
@@ -0,0 +1,347 @@
...
+				};
+
+				port@3 {
+					reg = <3>;
+					label = "lan1";
+				};
+
+				port@4 {
+					reg = <4>;
+					label = "wan";
```
Comment (dangowrt) [inline target/linux/mediatek/dts/mt7981b-asus-rt-ax57m.dts:149]: MAC address from nvmem for WAN...?

File: target/linux/mediatek/dts/mt7981b-asus-rt-ax57m.dts [hunk 8]
```diff
@@ -0,0 +1,347 @@
...
+		precal_factory_1010: precal@1010 {
+			reg = <0x1010 0x6f010>;
+		};		
+	};
+};
+
+&spi1 {
+	pinctrl-names = "default";
+	pinctrl-0 = <&spic_pins>;
+	status = "disabled";
```
Comment (dangowrt) [inline target/linux/mediatek/dts/mt7981b-asus-rt-ax57m.dts]: Why add it if it is disabled? Just remove all of `spi1` then.

File: target/linux/mediatek/dts/mt7981b-asus-rt-ax57m.dts [hunk 9]
```diff
@@ -0,0 +1,347 @@
...
+
+&wifi {
+	nvmem-cells = <&eeprom_factory_0>, <&precal_factory_1010>;
+	nvmem-cell-names = "eeprom", "precal";
+
+	status = "okay";
+};
+
+&xhci {
+	mediatek,u3p-dis-msk = <0x0>;
```
Comment (dangowrt) [inline target/linux/mediatek/dts/mt7981b-asus-rt-ax57m.dts]: 0x0 is the default afaik, you can just omit this property if both USB2 and USB3 pins are connected for this port.

**Review by dangowrt — CHANGES_REQUESTED** [review]

**Comment by nam-van-nguyen** [comment]
> @warrenmr @nam-van-nguyen see [#21236 (comment)](https://github.com/openwrt/openwrt/pull/21236#issuecomment-3678235358) for a build of the 24.10 stable version with functional WAN.

Thank you.  I can confirm that the code built and run very well on all ports (I bridge all ports Lan1-4 and WAN, and use VLAN to create various network and trunk line).

File: target/linux/mediatek/dts/mt7981b-asus-rt-ax57m.dts (hunk 7 above)
Comment (dangowrt) [reply target/linux/mediatek/dts/mt7981b-asus-rt-ax57m.dts:149]: Sorry, forget about this one, LAN and WAN MAC are identical on this device, I forgot.

File: target/linux/mediatek/dts/mt7981b-asus-rt-ax57m.dts (hunk 8 above)
Comment (theofficialgman) [reply target/linux/mediatek/dts/mt7981b-asus-rt-ax57m.dts]: copied by @remittor from the ax52.

Checking the vendor's official device tree, `spi1` (just called `spi@1100b000` in vendor and upstream linux kernel) is disabled. Its also disabled in upstream linux kernel and in the patched `mt7981b.dtsi` from openwrt. I don't think setting the pinctrl values has any purpose if its disabled so I will remove it from this.

File: target/linux/mediatek/dts/mt7981b-asus-rt-ax57m.dts (hunk 9 above)
Comment (theofficialgman) [reply target/linux/mediatek/dts/mt7981b-asus-rt-ax57m.dts]: added by @remittor. the ax57m does not have usb2/usb3 ports (and I don't even see one internally on ax57m, not sure if they are used to connect to some internal peripheral that I'm missing).

my guess is this is a holdover from the vendor device tree where xhci is enabled for some reason:

```
	xhci@11200000 {
		compatible = "mediatek,mt7986-xhci\0mediatek,mtk-xhci";
		reg = <0x00 0x11200000 0x00 0x2e00 0x00 0x11203e00 0x00 0x100>;
		reg-names = "mac\0ippc";
		interrupts = <0x00 0xad 0x04>;
		phys = <0x18 0x03 0x0d 0x04>;
		clocks = <0x19 0x19 0x19 0x19 0x19>;
		clock-names = "sys_ck\0xhci_ck\0ref_ck\0mcu_ck\0dma_ck";
		#address-cells = <0x02>;
		#size-cells = <0x02>;
		mediatek,u3p-dis-msk = <0x00>;
		status = "okay";
	};

	usb-phy@11e10000 {
		compatible = "mediatek,mt7986\0mediatek,generic-tphy-v2";
		#address-cells = <0x02>;
		#size-cells = <0x02>;
		ranges;
		status = "okay";

		usb-phy@11e10000 {
			reg = <0x00 0x11e10000 0x00 0x700>;
			clocks = <0x19>;
			clock-names = "ref";
			#phy-cells = <0x01>;
			status = "okay";
			phandle = <0x18>;
		};

		usb-phy@11e10700 {
			reg = <0x00 0x11e10700 0x00 0x900>;
			clocks = <0x19>;
			clock-names = "ref";
			#phy-cells = <0x01>;
			mediatek,syscon-type = <0x13 0x218 0x00>;
			nvmem-cells = <0x1a 0x1b 0x1c>;
			nvmem-cell-names = "intr\0rx_imp\0tx_imp";
			status = "okay";
			phandle = <0x0d>;
		};
	};
```

looking at openwrt's patched `mt7981b.dtsi` xhci and `usb-phy` are disabled by default, so I will try with just removing `xhci` from the ax57m.dts

Comment (theofficialgman) [reply target/linux/mediatek/dts/mt7981b-asus-rt-ax57m.dts]: seems fine with that change.

File: target/linux/mediatek/dts/mt7981b-asus-rt-ax57m.dts (hunk 8 above)
Comment (theofficialgman) [reply target/linux/mediatek/dts/mt7981b-asus-rt-ax57m.dts]: seems fine with that change

**Comment by theofficialgman** [comment]
The backport PR's have now been updated to what has been merged into main.

https://github.com/openwrt/openwrt/pull/21236
https://github.com/openwrt/openwrt/pull/21237
