### PR TITLE
armsr: preserve configuration during sysupgrade

### LINKED ISSUE #13695: armsr: sysupgrade loses settings with the squashfs image
### Describe the bug

Applying an armsr armv8 squashfs image via sysupgrade wipes the configuration instead of preserving it.

### OpenWrt version

r23497-6637af95aa

### OpenWrt target/subtarget

armsr/armv8

### Device

QEMU QEMU Virtual Machine

### Image kind

Official downloaded image

### Steps to reproduce

Apply an armsr armv8 squashfs image via sysupgrade
I tried 23.05.0-rc4 -> 23.05.0 and 23.05.0 -> 23.05.0

### Actual behaviour

The update applies, but all configuration is lost

### Expected behaviour

Keep the configuration

### Additional info

This does not affect the ext4 images.

CC @mcbridematt 

### Diffconfig

_No response_

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

### PR DESCRIPTION
**Pull request by Kistelini**
Fixes: https://github.com/openwrt/openwrt/issues/13695

This also needs a backport to 23.05.

### CODE REVIEW

File: target/linux/armsr/base-files/lib/upgrade/platform.sh [hunk 1]
```diff
@@ -34,10 +34,10 @@ platform_check_image() {
 }
 
 platform_copy_config() {
-	local partdev parttype=ext4
+	local partdev
 
-	if export_partdevice partdev 2; then
-		mount -t $parttype -o rw,noatime "/dev/$partdev" /mnt
+	if export_partdevice partdev 1; then
+		mount -t vfat -o rw,noatime "/dev/$partdev" /mnt
```
Comment (Ansuel) [inline target/linux/armsr/base-files/lib/upgrade/platform.sh:40]: No... check x86... part_magic_fat should be used instead of hardcoding... Also can you explain why 2 was changed to 1?

File: target/linux/armsr/base-files/lib/preinit/79_move_config [hunk 2]
```diff
@@ -0,0 +1,18 @@
+# SPDX-License-Identifier: GPL-2.0-only
+
+move_config() {
+	local partdev
+
+	. /lib/upgrade/common.sh
+
+	if export_bootdevice && export_partdevice partdev 1; then
+		if mount -t vfat -o rw,noatime "/dev/$partdev" /mnt; then
```
Comment (Ansuel) [inline target/linux/armsr/base-files/lib/preinit/79_move_config:9]: No hardcoding... use part_magic_fat.... actually this can be just a copy of the x86 file...

File: target/linux/armsr/base-files/lib/upgrade/platform.sh (hunk 1 above)
Comment (Kistelini) [reply target/linux/armsr/base-files/lib/upgrade/platform.sh]: Partition 1 is the boot partition whereas partition 2 is either ext4 or squashfs. If it's the latter it wouldn't be writable.

File: target/linux/armsr/base-files/lib/preinit/79_move_config (hunk 2 above)
Comment (Kistelini) [reply target/linux/armsr/base-files/lib/preinit/79_move_config]: Changed, but the boot partition should always be fat?

**Comment by Ansuel** [comment]
@Kistelini can you add a commit description? Aside from this this is ok and I will merge with last change.

**Comment by Kistelini** [comment]
Done!

**Comment by Ansuel** [comment]
Think you pushed the wrong change and you reverted the changes I requested!

**Comment by Kistelini** [comment]
Oops :facepalm:
